# Generated by Django 5.1 on 2024-08-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicharsagar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='related_topics', to='vicharsagar.topic'),
        ),
        migrations.AlterField(
            model_name='article',
            name='articleImage',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
