# Generated by Django 5.1 on 2024-08-30 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicharsagar', '0002_article_topics_alter_article_articleimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('push_notification', models.BooleanField(default=True)),
                ('email_notification', models.BooleanField(default=True)),
                ('theme', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('articles', models.ManyToManyField(blank=True, related_name='user_articles', to='vicharsagar.article')),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('lists', models.ManyToManyField(blank=True, related_name='user_lists', to='vicharsagar.list')),
                ('topics', models.ManyToManyField(blank=True, related_name='user_topics', to='vicharsagar.topic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
