# Generated by Django 5.1 on 2024-09-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicharsagar', '0005_list_user_alter_list_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='articles',
            field=models.ManyToManyField(blank=True, to='vicharsagar.article'),
        ),
    ]
